// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ijbxeeckEHi65171SrnxaJU9y5TaTIw',
    appId: '1:856710108082:android:e9f9d5002fa27f008ccaab',
    messagingSenderId: '856710108082',
    projectId: 'my-film-af367',
    databaseURL: 'https://my-film-af367-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-film-af367.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtIr5S4o7XI0cCG4ZsplA_84JRv4XFmTE',
    appId: '1:856710108082:ios:575323f831a0da3c8ccaab',
    messagingSenderId: '856710108082',
    projectId: 'my-film-af367',
    databaseURL: 'https://my-film-af367-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-film-af367.firebasestorage.app',
    androidClientId: '856710108082-0kjsk740q15dua06c8ap2bti6hi2icfo.apps.googleusercontent.com',
    iosClientId: '856710108082-rqcrsmc8j7hkr2rs2j4u0i56r0t8nljf.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfilm',
  );
}
